language: python
python:
- "3.4"


addons:
  apt:
    sources:
      pyqt5
    packages:
      qt5


install:
  - pip install -r requirements.txt


script:
  - alias python='python2'
  - nuitka --recurse-all --standalone --improved --python-version=3.4 --python-flag=no_site program.py
