language: python
python:
- "2.7"
- "3.4"

matrix:
  exclude:
    - python: "2.7"

install:
  - "pip install -r requirements.txt"

script:
  - nuitka --recurse-all --standalone --improved --python-version=3.4 --python-flag=no_site Program.py
